apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    type: local
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/nfs"
    server: "192.168.1.22"
  persistentVolumeReclaimPolicy: Retain
